// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/protocol.proto

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ItemType int32

const (
	ItemType_USERITEM  ItemType = 0
	ItemType_EQUIPMENT ItemType = 1
)

var ItemType_name = map[int32]string{
	0: "USERITEM",
	1: "EQUIPMENT",
}
var ItemType_value = map[string]int32{
	"USERITEM":  0,
	"EQUIPMENT": 1,
}

func (x ItemType) String() string {
	return proto.EnumName(ItemType_name, int32(x))
}
func (ItemType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0d784fc8bac33d4d, []int{0}
}

type ItemInfo struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=Type" json:"Type,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
	Amount               int32    `protobuf:"varint,4,opt,name=Amount" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemInfo) Reset()         { *m = ItemInfo{} }
func (m *ItemInfo) String() string { return proto.CompactTextString(m) }
func (*ItemInfo) ProtoMessage()    {}
func (*ItemInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0d784fc8bac33d4d, []int{0}
}
func (m *ItemInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemInfo.Unmarshal(m, b)
}
func (m *ItemInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemInfo.Marshal(b, m, deterministic)
}
func (dst *ItemInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemInfo.Merge(dst, src)
}
func (m *ItemInfo) XXX_Size() int {
	return xxx_messageInfo_ItemInfo.Size(m)
}
func (m *ItemInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ItemInfo proto.InternalMessageInfo

func (m *ItemInfo) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ItemInfo) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ItemInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ItemInfo) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*ItemInfo)(nil), "protocol.ItemInfo")
	proto.RegisterEnum("protocol.ItemType", ItemType_name, ItemType_value)
}

func init() { proto.RegisterFile("protocol/protocol.proto", fileDescriptor_protocol_0d784fc8bac33d4d) }

var fileDescriptor_protocol_0d784fc8bac33d4d = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x87, 0x31, 0xf4, 0xc0, 0x0c, 0x21, 0x0e, 0x18, 0x5f, 0x29, 0x8a,
	0x8b, 0xc3, 0xb3, 0x24, 0x35, 0xd7, 0x33, 0x2f, 0x2d, 0x5f, 0x88, 0x8f, 0x8b, 0xc9, 0xd3, 0x45,
	0x82, 0x51, 0x81, 0x51, 0x83, 0x35, 0x88, 0xc9, 0xd3, 0x45, 0x48, 0x88, 0x8b, 0x25, 0xa4, 0xb2,
	0x20, 0x55, 0x82, 0x09, 0x2c, 0x02, 0x66, 0x83, 0xc4, 0xfc, 0x12, 0x73, 0x53, 0x25, 0x98, 0x15,
	0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x31, 0x2e, 0x36, 0xc7, 0xdc, 0xfc, 0xd2, 0xbc, 0x12,
	0x09, 0x16, 0xb0, 0x4a, 0x28, 0x4f, 0x4b, 0x1d, 0x62, 0x36, 0x58, 0x1f, 0x0f, 0x17, 0x47, 0x68,
	0xb0, 0x6b, 0x90, 0x67, 0x88, 0xab, 0xaf, 0x00, 0x83, 0x10, 0x2f, 0x17, 0xa7, 0x6b, 0x60, 0xa8,
	0x67, 0x80, 0xaf, 0xab, 0x5f, 0x88, 0x00, 0x63, 0x12, 0x1b, 0xd8, 0x39, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x90, 0x33, 0xb1, 0xfd, 0xb0, 0x00, 0x00, 0x00,
}
