// Code generated by protoc-gen-go.
// source: protocol.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	protocol.proto

It has these top-level messages:
	ItemInfo
*/
package protocol

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type ItemType int32

const (
	ItemType_USERITEM  ItemType = 0
	ItemType_EQUIPMENT ItemType = 1
)

var ItemType_name = map[int32]string{
	0: "USERITEM",
	1: "EQUIPMENT",
}
var ItemType_value = map[string]int32{
	"USERITEM":  0,
	"EQUIPMENT": 1,
}

func (x ItemType) String() string {
	return proto.EnumName(ItemType_name, int32(x))
}

type ItemInfo struct {
	ID     int32  `protobuf:"varint,1,opt" json:"ID,omitempty"`
	Type   int32  `protobuf:"varint,2,opt" json:"Type,omitempty"`
	Name   string `protobuf:"bytes,3,opt" json:"Name,omitempty"`
	Amount int32  `protobuf:"varint,4,opt" json:"Amount,omitempty"`
}

func (m *ItemInfo) Reset()         { *m = ItemInfo{} }
func (m *ItemInfo) String() string { return proto.CompactTextString(m) }
func (*ItemInfo) ProtoMessage()    {}

func init() {
	proto.RegisterEnum("protocol.ItemType", ItemType_name, ItemType_value)
}
